[build-system]
requires = [
  "setuptools >= 47.0.0",
  "wheel",
  "setuptools_scm[toml] >= 3.4",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "SpatialDE/version.py"

[tool.black]
line-length = 100
target-version = ['py37']
